[project]
name = "gateway-api"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name", email = "you@example.com"}
]
readme = "README.md"
requires-python = ">3.13,<4.0.0"
dependencies = [
    "flask>=3.1.2,<4.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-flask>=1.3.0",
    "pytest-html>=4.0.0",
    "pytest-cov>=6.0.0",
    "pact-python>=2.0.0",
    "requests>=2.31.0",
    "behave>=1.3.3",
    "behave-html-pretty-formatter>=1.15.1",
    "schemathesis>=4.4.1",
]

[tool.poetry]
packages = [{include = "gateway_api", from = "src"}]

[tool.coverage.run]
relative_files = true

[tool.coverage.xml]
output = "coverage.xml"

[tool.coverage.html]
directory = "htmlcov"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
